apiVersion: apps/v1
kind: Deployment
metadata:
  name: facebookservice-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: facebookservice
  template:
    metadata:
      labels:
        app: facebookservice
    spec:
      containers:
        - name: facebookservice
          image: vizelog/facebookservice
---
apiVersion: v1
kind: Service
metadata:
  name: facebookservice-srv
spec:
  selector:
    app: facebookservice
  ports:
    - name: facebookservice
      protocol: TCP
      port: 3000
      targetPort: 3000