apiVersion: apps/v1
kind: Deployment
metadata:
  name: instagramservice-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: instagramservice
  template:
    metadata:
      labels:
        app: instagramservice
    spec:
      containers:
        - name: instagramservice
          image: vizelog/instagramservice
---
apiVersion: v1
kind: Service
metadata:
  name: instagramservice-srv
spec:
  selector:
    app: instagramservice
  ports:
    - name: instagramservice
      protocol: TCP
      port: 3000
      targetPort: 3000