apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiktokservice-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tiktokservice
  template:
    metadata:
      labels:
        app: tiktokservice
    spec:
      containers:
        - name: tiktokservice
          image: vizelog/tiktokservice
---
apiVersion: v1
kind: Service
metadata:
  name: tiktokservice-srv
spec:
  selector:
    app: tiktokservice
  ports:
    - name: tiktokservice
      protocol: TCP
      port: 3000
      targetPort: 3000