apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitterservice-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twitterservice
  template:
    metadata:
      labels:
        app: twitterservice
    spec:
      containers:
        - name: twitterservice
          image: vizelog/twitterservice
---
apiVersion: v1
kind: Service
metadata:
  name: twitterservice-srv
spec:
  selector:
    app: twitterservice
  ports:
    - name: twitterservice
      protocol: TCP
      port: 3000
      targetPort: 3000