name: tests-youtubeservice

on:
  pull_request:
    paths:
      - 'youtubeservice/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd youtubeservice && npm install && npm run test:ci
